[[snippets]]
  description = "docker kill all"
  command = "docker kill `docker ps -q`"
  tag = ["docker", "kill", "all"]
  output = ""

[[snippets]]
  description = "kill all chrome pids"
  command = "ps -ef | grep -i [c]hrom | awk '{print $2}' | xargs kill -9"
  tag = ["kill", "chrome", "chromium", "prerender", "all"]
  output = ""

[[snippets]]
  description = "sample terminal colors"
  command = "msgcat --color=test"
  output = ""
